### ISSUE TITLE
[ENHANCEMENT] Queller Sub commanders play sub optimally on Foundation home system

### ISSUE THREAD

**Issue by laodie666** [Quitch/GW-AI-Overhaul#10]
## Attestation

[yes] I have verified this bug with all other mods disabled

[yes] I did not create this war while using one of the documented incompatible mods

## Describe the bug

The sub commanders play on the gold brain while the enemy play on the uber brain, which means the enemy is a lot better at designating their resource usage and interplanetary warfare. This isn't much of a problem in a smaller system, but when there are multiple planets and multiple spawns, my sub commanders are unable to go orbital and tech up. They simply proceed to spam ground units after clearing the planet and lag the game

## To Reproduce

Steps to reproduce the behaviour:

1. Play on any multi-planetary system with spawns available on multiple planets. Boss level such as the foundation suffers from this problem the most. 
2.  clear out all enemy ground forces on the spawning planet, and go into the orbital phase. 
3. enter a stalemate with both sides trying to tech up. 
4. Sub commander proceeds to spam ground unit nonstop and doesn't tech up, lagging the game in the process

## Expected behaviour

In my opinion, sub commanders should also use uber brains but with an econ nerf. Something like 0.9 econ rate or 0.85 would make them capable of playing the game but not so strong they can just carry the players by themselves. This could be an optional setting in a custom galaxy tho I feel it should be the default setting. I think this is a suitable change as I don't feel there is that big of a difference between uber and gold ground combat, as, with the appropriate cards, my sub commanders can often 1v2 enemy despite being outsmarted. However, in the late game, the gold commander is useless and simply lags the game while the enemy adapts to the situation. 

## Screenshots

I don't have a screenshot of my game tho I checked the stats and my sub commanders built around 1000 units each after the enemy got cleared out. I have a lot of econ tech but they invest all the money into tier 1 ground units. 

## GWO Info

Taken from the top-right GWO panel:

- Version: 5.27.0
- Difficulty: Gold
- Size: Epic
- AI: Queller
- Options: Faction scaling, Easier start

## Logs
Git hub doesn't let me submit files for some reason and this isn't an actual bug, but rather an issue with the mod's design. It makes me unable to beat most bigger systems.

**Comment by Quitch** [comment]
I'll need your localstore to investigate.

**Comment by laodie666** [comment]
https://drive.google.com/drive/folders/1wly7ZXKvlDpEmwC2XqcG-DyTTlfUSsO6?usp=sharing
git hub does not let me upload file cuz its bugged I think so ima just share a link

**Comment by Quitch** [comment]
Are you extrapolating for systems other than the Foundation boss world, or do you have examples of that too?

**Comment by laodie666** [comment]
Nvm i think it's a specific case with the foundation. My subcommanders seem to be able to function properly in a normal system. The Foundation is prob broken cuz the AI has no idea how to invade a sea planet considering there is basically no land on it.

**Comment by laodie666** [comment]
I think this problem isn't due to orbital, but more related to any sea warfare. The AI doesn't realize their land units can't walk on sea and thus doesn't invest in navy or hovercraft. 
![image](https://user-images.githubusercontent.com/93632952/163869670-ee64b79f-e9c8-4245-ab0d-99995b74e4b2.png)

**Comment by Quitch** [comment]
That's an issue unrelated to this mod.

**Comment by Quitch** [comment]
This appears to be an AI engine issue which would make this a CANTFIX.
