### ISSUE TITLE
[BUG] Slammer Upgrade Tech - Topedoes dive into ground

### ISSUE THREAD

**Issue by Lula-Mae** [Quitch/GW-AI-Overhaul#108]
After receiving the Slammer Upgrade tech card, the Slammer torpedoes dive into ground instead of flying trough the air.

Video - https://www.youtube.com/watch?v=STE4gubtQN8

Localstore folder at https://drive.google.com/drive/folders/1eYJ1B5zbptk9UOQfvOuSjN0brJ6JEL80?usp=sharing

[server-2024-04-22_073323.txt](https://github.com/Quitch/GW-AI-Overhaul/files/15062576/server-2024-04-22_073323.txt)
[PA-2024-04-22_072245.txt](https://github.com/Quitch/GW-AI-Overhaul/files/15062578/PA-2024-04-22_072245.txt)

**Comment by Quitch** [comment]
This is fixed by https://github.com/Quitch/GW-AI-Overhaul/commit/96fe7186ea479a429f64c249d082e87f0f186780, which will be in tomorrow's release
