### ISSUE TITLE
[BUG] Can't move in Galactic Map (no jump button)

### ISSUE THREAD

**Issue by Friekohw** [Quitch/GW-AI-Overhaul#121]
Hi Quitch, 

As per the title,

Tell me what you need from me!

**Comment by Quitch** [comment]
All the stuff that's requested in the bug report template.

**Comment by Friekohw** [comment]
Hi Q,

Sorry, first time uploading something like this, wasn't able to find a file name Server - XX - PP - ECT
![Screenshot 2024-07-26 221132](https://github.com/user-attachments/assets/dbbbf208-9e3f-40bd-8265-45caf194b891)

Hope this helps

Version: 120799
Difficulty: Silver
Size: Marathon
AI: Penchant
Options: Sys / Fac scaling - Sys lore
 

[6c9c25aa-91bd-4bf6-8ebf-448646a5ca60.dmp](https://github.com/user-attachments/files/16395852/6c9c25aa-91bd-4bf6-8ebf-448646a5ca60.dmp)
[PA-2024-07-24_185504.txt](https://github.com/user-attachments/files/16395853/PA-2024-07-24_185504.txt)
[PA-2024-07-24_205253.txt](https://github.com/user-attachments/files/16395854/PA-2024-07-24_205253.txt)

**Comment by Quitch** [comment]
Please also upload and link a copy of your localstore folder, found within the [Planetary Annihilation Data Directory](https://support.planetaryannihilation.com/kb/faq.php?id=176).

**Comment by Stormepidemic** [comment]
I have also experienced this issue. I loaded up to play today, 7/26/2024 and was very disappointed to not be able to continue my campaign. 
![image](https://github.com/user-attachments/assets/c575a8de-533a-430f-93a0-f090891ceceb)
(Yes, I know those mods are incompatible but I have been playing this same save for about a week and just found this problem today)
[Game Data.zip](https://github.com/user-attachments/files/16398035/Game.Data.zip)

**Comment by jacob0131** [comment]
I have the same bug. Yesterday I played it well on my PC, but today when I played it on my laptop the jump button disappeared.
![image](https://github.com/user-attachments/assets/87e2207e-17cf-40d5-a57e-5b888c21facd)
PA titan Version: 120799

my data dic folder 
[Planetary Annihilation.zip](https://github.com/user-attachments/files/16398140/Planetary.Annihilation.zip)
)

**Comment by Quitch** [comment]
I've tried both saves and it doesn't break for me, therefore I'm going to need you to confirm and then try a few things for me:

1. You are running PA TITANS not PA
6. You have verified your game files through Steam
7. Whether v5.66.1 fixes the issue (it should be live in an hour or so)

Can you provide me exact step-by-step (click-by-click) instructions on what you're doing and what you're seeing? For example:

1. Load PA
2. Go into Galactic War lobby
3. Start new war
4. Click on system adjacent to starting position
5. Neither selection circle nor jump button appears

Following this, please try the following

1. Add `--coherent_port=9999` to your game launch options
2. Download the [coherent debugger](https://cdn.planetaryannihilation.com/downloads/debugger-windows.zip)
3. Extract the debugger to any folder
4. Start PA
5. Load the debugger
6. Click GO in the debugger
7. Select "Start Page" from the inspectable page list (if it doesn't show then click GO again until it does)
8. Click "Console" from the top row
9. Load into Galactic War
10. Paste the following code into the console and then press return:
```javascript
    model.canMove = ko.computed(function () {
      if (model.player.moving()) {
        return false;
      }
      const from = model.game().currentStar();
      const to = model.selection.star();
      console.log("From:", from, "To:", to)
      if (to < 0 || to > model.game().galaxy().stars().length) {
        console.log("Nope 1")
        return false;
      }
      if (!model.canSelectOrMovePrefix()) {
        console.log("Nope 2")
        return false;
      }
      if (from === to) {
        console.log("Nope 3")
        return false;
      }
      console.log("Path:", model.game().galaxy().pathBetween(from, to, model.cheats.noFog()))
      return model.game().galaxy().pathBetween(from, to, model.cheats.noFog());
    });
```
11. Click on a system you should be able to jump to and capture the console output generated. Also note whether the jump button was appearing.
12. Paste the following code into the console and then press return:
```javascript
    model.canMove = ko.computed(function () {
      if (model.player.moving()) {
        return false;
      }
      var from = model.game().currentStar();
      var to = model.selection.star();
      console.log("From:", from, "To:", to)
      if (to < 0 || to > model.game().galaxy().stars().length) {
        console.log("Nope 1")
        return false;
      }
      if (!model.canSelectOrMovePrefix()) {
        console.log("Nope 2")
        return false;
      }
      if (from === to) {
        console.log("Nope 3")
        return false;
      }
      console.log("Path:", model.game().galaxy().pathBetween(from, to, model.cheats.noFog()))
      return model.game().galaxy().pathBetween(from, to, model.cheats.noFog());
    });
```
13. Click on a system you should be able to jump to and capture the console output generated. Also note whether the jump button was appearing.
14. Enter the following into the console: `model.game().galaxy().pathBetween`
15. Capture the output
16. Report back here with the output from 11, 13, and 15.

**Comment by mjones8019** [comment]
Hi Q,

Thanks for looking into this.  I play with and love many of your mods, great game enhancements.  I am in a similar boat, unable to change systems in GW since what appears to be the 5.66 update.  I have tried a new GW, removing and installing the mod again, and restarting the game in various ways.  Here is a screenshot and the requested files.  Best of luck with the problem.
![image](https://github.com/user-attachments/assets/065bd1b4-92a6-4d71-8e43-03edd03f77c2)

a Link to my PA Data folder...(it is too large to attach here) -- https://drive.google.com/file/d/1qINtGLmHrGvH89kw2ifxAPnznwNbKv3L/view?usp=drive_link

Hope this helps.

**Comment by Quitch** [comment]
I get access denied on that link

**Comment by mjones8019** [comment]
Try it now, I changed the permissions on the link.  My bad.

**Comment by Quitch** [comment]
Thanks, I can get it now. If you could please also see [this post](https://github.com/Quitch/GW-AI-Overhaul/issues/121#issuecomment-2253973373), since the saves thus far aren't giving me the bug.

**Comment by mjones8019** [comment]
odd...could it be a conflict with another GW mod?  I also run Bigger Galactic War...and have a bunch others loaded, but they do not affect GW...  

I will go through the steps above and post the output.

**Comment by Quitch** [comment]
Usually a "works for me but not for thee" bug is a race condition somewhere.

**Comment by mjones8019** [comment]
Here is what I have.

11 -- "model.canMove = ko.computed(function () {
      if (model.player.moving()) {
        return false;
      }
      const from = model.game().currentStar();
      const to = model.selection.star();
      console.log("From:", from, "To:", to)
      if (to < 0 || to > model.game().galaxy().stars().length) {
        console.log("Nope 1")
        return false;
      }
      if (!model.canSelectOrMovePrefix()) {
        console.log("Nope 2")
        return false;
      }
      if (from === to) {
        console.log("Nope 3")
        return false;
      }
      console.log("Path:", model.game().galaxy().pathBetween(from, to, model.cheats.noFog()))
      return model.game().galaxy().pathBetween(from, to, model.cheats.noFog());
    });
VM2795:8 From: 34 To: 34
VM2795:18 Nope 3
boot.js:981 [object Object]
12gw_galaxy.js:82 Uncaught TypeError: Cannot read property 'history' of undefinedgw_galaxy.js:82 self.pathBetweengw_play.js:1117 self.canSelectgw_play.js:1189 (anonymous function)boot.js:969 D.notifySubscribersboot.js:974 F.xaboot.js:973 cgw_play.js:321 (anonymous function)easeljs-0.7.1.min.js:12 b._dispatchEventeaseljs-0.7.1.min.js:12 b.dispatchEventeaseljs-0.7.1.min.js:13 b._dispatchMouseEventeaseljs-0.7.1.min.js:13 b._handlePointerUpeaseljs-0.7.1.min.js:13 b._handleMouseUpeaseljs-0.7.1.min.js:13 b.enableDOMEvents.d.mouseup.f"

13 --model.canMove = ko.computed(function () {
      if (model.player.moving()) {
        return false;
      }
      var from = model.game().currentStar();
      var to = model.selection.star();
      console.log("From:", from, "To:", to)
      if (to < 0 || to > model.game().galaxy().stars().length) {
        console.log("Nope 1")
        return false;
      }
      if (!model.canSelectOrMovePrefix()) {
        console.log("Nope 2")
        return false;
      }
      if (from === to) {
        console.log("Nope 3")
        return false;
      }
      console.log("Path:", model.game().galaxy().pathBetween(from, to, model.cheats.noFog()))
      return model.game().galaxy().pathBetween(from, to, model.cheats.noFog());
    });
VM2808:8 From: 34 To: 34
VM2808:18 Nope 3
boot.js:981 [object Object]
gw_galaxy.js:82 Uncaught TypeError: Cannot read property 'history' of undefinedgw_galaxy.js:82 self.pathBetweengw_play.js:1117 self.canSelectgw_play.js:1189 (anonymous function)boot.js:969 D.notifySubscribersboot.js:974 F.xaboot.js:973 cgw_play.js:321 (anonymous function)easeljs-0.7.1.min.js:12 b._dispatchEventeaseljs-0.7.1.min.js:12 b.dispatchEventeaseljs-0.7.1.min.js:13 b._dispatchMouseEventeaseljs-0.7.1.min.js:13 b._handlePointerUpeaseljs-0.7.1.min.js:13 b._handleMouseUpeaseljs-0.7.1.min.js:13 b.enableDOMEvents.d.mouseup.f"

15 -- model.game().galaxy().pathBetween
gw_galaxy.js:41 function (from, to, noFog) {
      const toExplored = self.stars()[to].explored();

      const neighborsMap = self.neighborsMap();

      const checked = {};

      const workList = [[from]];

      while (workList.length > 0) {
        const path = workList.shift();

        const node = path[path.length - 1];
        const nodeNeighbors = neighborsMap[node];

        checked[node] = true;

        for (const neighbor of nodeNeighbors) {
          const other = neighbor;

          if (checked[other]) {
            continue;
          } // ignore loop

          if (other === to) {
            const previous = _.last(path);

            // prevent pathing through unexplored systems for fog of war

            const explored = self.stars()[previous].explored() || toExplored;

            if (!explored && !noFog) {
              continue;
            }

            path.push(other);

            return path;
          }

          const otherStar = self.stars()[other];
          const otherVisited = otherStar.history().length > 0;

          const valid = noFog ? otherVisited : otherStar.explored();

          if (valid) {
            const newPath = _.cloneDeep(path);
            newPath.push(other);

            workList.push(newPath);
          }
        }
      }

      return null;
    }

**Comment by mjones8019** [comment]
and, to make sure it is not a conflict, I disabled all other mods but global chat, started a new GW, and here they are too...look the same to me.

11 -- 
 Uncaught TypeError: Cannot read property 'history' of undefinedgw_galaxy.js:82 self.pathBetweengw_play.js:1117 self.canSelectgw_play.js:1189 (anonymous function)boot.js:969 D.notifySubscribersboot.js:974 F.xaboot.js:973 cgw_play.js:321 (anonymous function)easeljs-0.7.1.min.js:12 b._dispatchEventeaseljs-0.7.1.min.js:12 b.dispatchEventeaseljs-0.7.1.min.js:13 b._dispatchMouseEventeaseljs-0.7.1.min.js:13 b._handlePointerUpeaseljs-0.7.1.min.js:13 b._handleMouseUpeaseljs-0.7.1.min.js:13 b.enableDOMEvents.d.mouseup.f

13 --
 Uncaught TypeError: Cannot read property 'history' of undefinedgw_galaxy.js:82 self.pathBetweengw_play.js:1117 self.canSelectgw_play.js:1189 (anonymous function)boot.js:969 D.notifySubscribersboot.js:974 F.xaboot.js:973 cgw_play.js:321 (anonymous function)easeljs-0.7.1.min.js:12 b._dispatchEventeaseljs-0.7.1.min.js:12 b.dispatchEventeaseljs-0.7.1.min.js:13 b._dispatchMouseEventeaseljs-0.7.1.min.js:13 b._handlePointerUpeaseljs-0.7.1.min.js:13 b._handleMouseUpeaseljs-0.7.1.min.js:13 b.enableDOMEvents.d.mouseup.f

15 --
 function (from, to, noFog) {
      const toExplored = self.stars()[to].explored();

      const neighborsMap = self.neighborsMap();

      const checked = {};

      const workList = [[from]];

      while (workList.length > 0) {
        const path = workList.shift();

        const node = path[path.length - 1];
        const nodeNeighbors = neighborsMap[node];

        checked[node] = true;

        for (const neighbor of nodeNeighbors) {
          const other = neighbor;

          if (checked[other]) {
            continue;
          } // ignore loop

          if (other === to) {
            const previous = _.last(path);

            // prevent pathing through unexplored systems for fog of war

            const explored = self.stars()[previous].explored() || toExplored;

            if (!explored && !noFog) {
              continue;
            }

            path.push(other);

            return path;
          }

          const otherStar = self.stars()[other];
          const otherVisited = otherStar.history().length > 0;

          const valid = noFog ? otherVisited : otherStar.explored();

          if (valid) {
            const newPath = _.cloneDeep(path);
            newPath.push(other);

            workList.push(newPath);
          }
        }
      }

      return null;
    }

seems the same to me, but I am not much of a coder or debugger.

**Comment by Quitch** [comment]
For 15, was that from a 5.66.0 war or an earlier one? If 5.66.0 can you load a save and see if you get the same output?

**Comment by mjones8019** [comment]
okay.  this is from a GWO 5.66 and War 5.65.1.

model.game().galaxy().pathBetween
gw_galaxy.js:41 function (from, to, noFog) {
      const toExplored = self.stars()[to].explored();

      const neighborsMap = self.neighborsMap();

      const checked = {};

      const workList = [[from]];

      while (workList.length > 0) {
        const path = workList.shift();

        const node = path[path.length - 1];
        const nodeNeighbors = neighborsMap[node];

        checked[node] = true;

        for (const neighbor of nodeNeighbors) {
          const other = neighbor;

          if (checked[other]) {
            continue;
          } // ignore loop

          if (other === to) {
            const previous = _.last(path);

            // prevent pathing through unexplored systems for fog of war

            const explored = self.stars()[previous].explored() || toExplored;

            if (!explored && !noFog) {
              continue;
            }

            path.push(other);

            return path;
          }

          const otherStar = self.stars()[other];
          const otherVisited = otherStar.history().length > 0;

          const valid = noFog ? otherVisited : otherStar.explored();

          if (valid) {
            const newPath = _.cloneDeep(path);
            newPath.push(other);

            workList.push(newPath);
          }
        }
      }

      return null;
    }

**Comment by Quitch** [comment]
OK, I think I have a workaround and if this works then v5.66.1 should fix this.

In the console paste the following and press return
```javascript
model.game().galaxy().pathBetween = function (from, to, noFog) {
        const toExplored = model.game().galaxy().stars()[to].explored();

        const neighborsMap = model.game().galaxy().neighborsMap();

        const checked = {};

        const workList = [[from]];

        while (workList.length > 0) {
          var path = workList.shift();

          var node = path[path.length - 1];
          var nodeNeighbors = neighborsMap[node];

          checked[node] = true;

          for (var neighbor of nodeNeighbors) {
            var other = neighbor;

            if (checked[other]) {
              continue;
            } // ignore loop

            if (other === to) {
              var previous = _.last(path);

              // prevent pathing through unexplored systems for fog of war

              var explored = model.game().galaxy().stars()[previous].explored() || toExplored;

              if (!explored && !noFog) {
                continue;
              }

              path.push(other);

              return path;
            }

            var otherStar = model.game().galaxy().stars()[other];
            var otherVisited = otherStar.history().length > 0;

            var valid = noFog ? otherVisited : otherStar.explored();

            if (valid) {
              var newPath = _.cloneDeep(path);
              newPath.push(other);

              workList.push(newPath);
            }
          }
        }

        return null;
      };
```
Then see if you can select systems.

**Comment by mjones8019** [comment]
Amazing!  After entereing that into console, while the same GW was still up, I then clicked on a target system and the jump button works and no error in console!!   You're a wizard!

**Comment by mjones8019** [comment]
Repeated jumps are working as normal as well.   Oh, and I reloaded all my mods, so it's super good!

**Comment by Quitch** [comment]
I think you will need to do that each time you return to the strategic map, until the new update goes live.

**Comment by mjones8019** [comment]
I can do that.  Thank You so much!  Putting the code in N++ now.

**Comment by Quitch** [comment]
@Stormepidemic @jacob0131 @Friekohw see [this post](https://github.com/Quitch/GW-AI-Overhaul/issues/121#issuecomment-2254082026) for the fix. You will need to use the [coherent debugger](https://github.com/Quitch/GW-AI-Overhaul/issues/121#issuecomment-2253973373) to implement it.

I believe when v5.66.1 goes live it will fix this. There are likely some other bugs tucked away in v5.66.0 due to the same underlying error which the next version fixes e.g. some cards may not apply properly.

**Comment by jacob0131** [comment]
i

> @Stormepidemic @jacob0131 @Friekohw[수정 사항 은 이 게시물을](https://github.com/Quitch/GW-AI-Overhaul/issues/121#issuecomment-2254082026) 참조하세요 . 이를 구현하려면 [coherent 디버거를](https://github.com/Quitch/GW-AI-Overhaul/issues/121#issuecomment-2253973373) 사용해야 합니다 .
> 
> v5.66.1이 출시되면 이 문제가 해결될 것으로 믿습니다. 다음 버전에서 수정되는 동일한 기본 오류로 인해 v5.66.0에 숨겨진 다른 버그가 있을 가능성이 있습니다. 예를 들어 일부 카드가 제대로 적용되지 않을 수 있습니다.


I followed along and it was fixed. wow thanks!!

**Comment by Quitch** [comment]
Version 5.66.1 is now live. Let me know if this fixes things.

**Comment by chrisbrookes** [comment]
Fixed it for me. Thx.

**Comment by Stormepidemic** [comment]
Fixed! Thank you Quitch!!

**Comment by Friekohw** [comment]
Hi Q,

Fixed for me too, sorry for the late reply, work :(

**Comment by mjones8019** [comment]
New patch is looking good!  Thanks for your diligence and dedication!
