### ISSUE TITLE
Galactic War map not responding

### ISSUE THREAD

**Issue by De4thless** [Quitch/GW-AI-Overhaul#122]
## Attestation

[x] I have verified this bug with all other mods disabled

[x] I am not running any [incompatible mods](https://github.com/Quitch/GW-AI-Overhaul#incompatible-mods)

[x] I am not running any [incompatible software](https://wiki.palobby.com/wiki/Windows_Incompatible_Software)

[x] I have confirmed this happens after [verifying the game's files](https://support.planetaryannihilation.com/kb/faq.php?id=188)

[x] I was using the latest [graphics drivers](https://support.planetaryannihilation.com/kb/faq.php?id=218)

## Describe the bug

After loading or creating Galactic War I cannot select any star on map. Log file returns "_ERROR [JS/game] coui://ui/main/game/galactic_war/shared/js/gw_galaxy.js:82: Uncaught TypeError: Cannot read property 'history' of undefined_".

## GWO Info

Taken from the top-right GWO panel:

- Version: 5.66.1 but this bug happened back in 10 October 2023
- Difficulty: Any
- Size: Uber
- AI: Any
- Options:

## Additional context

As I written in the description, problem is with file gw_galaxy.js line 82, variable **otherStar** is not defined. I replaced all code with vanilla and Galactic War map works.

## Logs

Please attach the most recent [client **AND** server logs](https://support.planetaryannihilation.com/kb/faq.php?id=182) immediately following the bug occurring. Pleas
e also upload and link a copy of your localstore folder, found within the [Planetary Annihilation Data Directory](https://support.planetaryannihilation.com/kb/faq.php?id=176).
[PA-2024-07-26_201630.txt](https://github.com/user-attachments/files/16398843/PA-2024-07-26_201630.txt)

**Comment by Quitch** [comment]
5.66.0 isn't out yet, so that can't be the version you're running.

I think you'll find that [this workaround](https://github.com/Quitch/GW-AI-Overhaul/issues/121#issuecomment-2254086612) fixes it.

**Comment by De4thless** [comment]
It works. I pretty much figured it out that the problem is in using **const** not **var**. Thank you for response. Waiting when 5.66.1 goes live.
