### ISSUE TITLE
[BUG] erratic application of Suddden Death modifier 

### ISSUE THREAD

**Issue by Lula-Mae** [Quitch/GW-AI-Overhaul#131]
Sometimes the Sudden Death game modifier is not applied as expected from the system preview.
Sometimes the Sudden Death game modifier is applied contrary to the system preview.
The Sudden Death Tech Card has NOT been selected.

In this most recent occurrence, the Sudden Death modifier was applied to the Legonis Machina faction on the Hatuamoto system contrary to the system preview as shown in the supplied screen shot.

The Cluster faction was still active when this occurred, so I immediately closed the game to save the files.
I was able to replay that system and duplicate the results. (and immediately close game with Cluster faction still active)
You might be able to restart that match from the supplied files?
Supporting files available at https://drive.google.com/drive/folders/1mqy2zY9MlGc_WivkKmmEk766zmJs-gfc

If needed, I can duplicate the results but complete the match and submit a new set of files.

**Comment by Lula-Mae** [comment]
Looking closer at the server file, the starting planet reads 

>"land_anywhere":true,"bounty_mode":true,"bounty_value":0.2,"sudden_death_mode":true

Whereas the preview mentions only Bounties.
This might be a broader issue than I initially thought.
There is typically only one game modifier applied per system, yes?

**Comment by Lula-Mae** [comment]
I have since seen where all 3 game modes were listed in the system preview

**Comment by Quitch** [comment]
I don't have access to the linked file.

**Comment by Lula-Mae** [comment]
Here is an example of the reverse. The preview for Naubakht system indicates Sudden Death mode but the server file has > "sudden_death_mode":false

Appropriate files located at https://drive.google.com/drive/folders/1qYCgf1YY8qsj5yQ-zhLHzvLAooJbCo4q
