### ISSUE TITLE
[BUG] JUMP option missing from selected systems

### ISSUE THREAD

**Issue by yourbigtony** [Quitch/GW-AI-Overhaul#2]
**Attestation**
PLEASE CONFIRM THAT YOU HAVE VERIFIED THIS BUG WITH ALL OTHER MODS DISABLED

**Describe the bug**
unable to move on galactic map.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '...' galactic war
2. Click on '....' next tile

**Expected behaviour**
unable to move to another tile on galactic war

**Screenshots**
![aaaaa](https://user-images.githubusercontent.com/85557288/121179565-ce131880-c857-11eb-8eee-fbe6a66e4b3a.png)

**GWO Info (taken from the top-right GWO panel):**
 - Version: 5.2.5
 - Difficulty: bronze
 - Size: large
 - AI: titans
 - Options: faction scaling, system scaling

**Comment by Quitch** [comment]
Attestation
PLEASE CONFIRM THAT YOU HAVE VERIFIED THIS BUG WITH ALL OTHER MODS DISABLED

**Comment by yourbigtony** [comment]
yes i can confirm the bug persists with all other mods turned off

it works normally without this mod

**Comment by Quitch** [comment]
Fixed by 4bcd78fe57a30496feb78f402aba0ad93792f79e
