### ISSUE TITLE
[BUG] Cluster causing server to crash after base scouted

### ISSUE THREAD

**Issue by Marxon1134** [Quitch/GW-AI-Overhaul#20]
## Attestation

[X ] I have verified this bug with all other mods disabled

[X ] I did not create this war while using one of the documented incompatible mods

## Describe the bug

Some battles with Cluster while running Penchant AI cause the game to hang up

## To Reproduce

Steps to reproduce the behaviour:

Galactic War
Fight cluster with colonel commander
Send units to their base
Hang occurs shortly after

## GWO Info

Taken from the top-right GWO panel:

- Version: 5.34.0
- Difficulty:Iron
- Size:Large
- AI:Penchant
- Options: Faction Scaling System Scaling Easier start

## Logs

Please attach the most recent [client and server log](https://support.planetaryannihilation.com/kb/faq.php?id=182) immediately following the bug occurring.
[PA Logs 6-13.zip](https://github.com/Quitch/GW-AI-Overhaul/files/8894524/PA.Logs.6-13.zip)

**Comment by Quitch** [comment]
Does this crash occur as soon as their units come into view, or after you've observed the base for some time?

Are you able to build a Colonel in sandbox mode without the game crashing?

Have you tried verifying your game files in Steam?

**Comment by Quitch** [comment]
User has not responded. Unable to replicate.

**Comment by Marxon1134** [comment]
It happens some time after gaining vision of the commander with units it
can also see, or it did...
Coincidentally the game experienced an update today and I am thankfully
unable to replicate the issue on the GW save, hoping it stays that way.
Will submit new report if issue occurs again.

**Comment by Quitch** [comment]
See #79
