### ISSUE TITLE
[BUG] AI not spawning in system

### ISSUE THREAD

**Issue by superawesomegoku** [Quitch/GW-AI-Overhaul#33]
## Attestation

[ ] I have verified this bug with all other mods disabled

[ ] I am not using one of the documented [incompatible mods](https://github.com/Quitch/GW-AI-Overhaul#incompatible-mods)

[ ] I have confirmed this happens after [verifying the games files](https://support.planetaryannihilation.com/kb/faq.php?id=188)

[ ] I was using the latest [graphics drivers](https://support.planetaryannihilation.com/kb/faq.php?id=218)

## Describe the bug

When I play on the Galatic War, enemy Commanders do not spawn at the start of the system. I and my sub-commanders are the only ones that spawn. By the time the intro sequence ends and I get to the surface, It brings up the "Victory" soundcard and gives me the win card. Why this happens I don't know, and I don't like the fact that I have to play around Tech landmines that break the game if I take them

## To Reproduce

I have found this error to happen when I have more than 2 Sub-Commanders, and I have the Commander Duplication Tech.

## Expected behaviour

I can play the game Normally

## Screenshots

![image](https://user-images.githubusercontent.com/31677211/178322514-008825b1-e3c1-4136-9a07-52112ea5c45a.png)

## GWO Info

Taken from the top-right GWO panel:

- Version: Current
- Difficulty: Diamond
- Size: Huge
- AI: 
- Options:

## Logs

Please attach the most recent [client and server log](https://support.planetaryannihilation.com/kb/faq.php?id=182) immediately following the bug occurring.

**Comment by Quitch** [comment]
Please update the issue with required attestations, steps to reproduce, GWO Info, and logs.

**Comment by laodie666** [comment]
encountered same issue with no apparently cause of issue.

my tab 
![image](https://user-images.githubusercontent.com/93632952/179094484-31dc4847-58fb-48f8-a1ad-edd6d3bd0138.png)

Log:
[server-2022-07-14_175225.txt](https://github.com/Quitch/GW-AI-Overhaul/files/9115733/server-2022-07-14_175225.txt)

**Comment by Quitch** [comment]
@laodie666 please open a new issue with details

**Comment by Quitch** [comment]
This should be fixed by https://github.com/Quitch/GW-AI-Overhaul/commit/fc40b72bd6d9921b861d9ef944ea5bc92ce64092
