### ISSUE TITLE
[BUG] Sub Commander is killing the gaming fun / The computer plays with itself

### ISSUE THREAD

**Issue by schittli** [Quitch/GW-AI-Overhaul#34]
Thanks a lot for sharing your great work!
Your Mod makes the Game fun. Usually... 😄:

## Attestation
[x] I have verified this bug with all other mods disabled
[x] I am not using one of the documented [incompatible mods]
[x] I have confirmed this happens after [verifying the games files]
[x] I was using the latest [graphics drivers]

## Describe the bug

As soon as one has the Sub Commander, "playing" the game is very easy:
1. Move your Commander to the Sub Commander Base
2. Wait until the Sub Commander has finished the mission
With the "Iron" difficulty, this works for 100%.

If one has no more challenges oneself, then the game is immediately no longer fun.

I suspect it's pretty hard to reduce the sub commander AI to help win the battle, but not guarantee it.

The description of the Sub Commander Tech Card would have to include at least a vigorous warning that if you play with it, that you yourself will become obsolete.

## To Reproduce

Steps to reproduce the behaviour:

1. With "Iron" difficulty (I don't know if this matters)
2. Start a game with the Sub Commander
3. Move your own Commander to the Sub Commander Base
4. Wait until the Sub Commander won the game.

## Expected behaviour

The Sub commander should not guarantee to win the game, but it should help to get it.

## GWO Info
Taken from the top-right GWO panel:
- Version: 5.39.2
- Difficulty: German: "Eisen" (Iron)
- Size: German: "Mittel" (Medium?)
- AI: German: "Titans" (Titan)
- Options: German: "Fraktionsskalierung, Systemskalierung" (Fraction scaling, system scaling)

Thanks a lot, kind regards,
Thomas

**Comment by Quitch** [comment]
Sub Commanders are unaffected by difficulty, the lower it is the better they are. I currently have no plans to change this.

**Comment by Quitch** [comment]
You can now select the sub commander AI brain independent of the enemy. You may find the Queller sub commanders without upgrades give you something closer to what you're looking for, as they're more defensive.
