### ISSUE TITLE
[BUG] Can build Omeaga's while using the Space excavation Commander

### ISSUE THREAD

**Issue by SV-Evillevi** [Quitch/GW-AI-Overhaul#35]
## Attestation
[ ] I have verified this bug with all other mods disabled
-[ ] I didn't verify that this bug works with all other mods disabled

[] I am not using one of the documented [incompatible mods](https://github.com/Quitch/GW-AI-Overhaul#incompatible-mods)
-[] I'm using the Section of Foreign Intelligence for galactic war. 

[X] I have confirmed this happens after [verifying the games files](https://support.planetaryannihilation.com/kb/faq.php?id=188)

[X] I was using the latest [graphics drivers](https://support.planetaryannihilation.com/kb/faq.php?id=218)

## Describe the bug

We can build Omega's while using the Space Excavation Commander even when it should be impossible. 

## To Reproduce

Steps to reproduce the behaviour:

1. Play Space Excavator commander
2. Get offered and select the complete orbital tech
3. You can build omega's even when the tool tips say it should noe be possible

## Expected behaviour

That the Omega's can't be build and that the Complete Orbital tech isn't offered
## GWO Info

Taken from the top-right GWO panel:

- Version:5.39.2
- Difficulty:Bronze
- Size:Large
- AI:Penchant
- Options:Faction Scaling + Easier start

**Comment by Quitch** [comment]
Please complete the attestations.

**Comment by SV-Evillevi** [comment]
OK :)

**Comment by Quitch** [comment]
Normally I wouldn't investigate an issue if you haven't verified it without other mods disabled, as they can interfere. You should also disabled Section of Foreign Intelligence for Galactic War as GWO comes with a modified copy with additional functionality and the original can cause issues with this.

Thankfully for you I had an idea as to the issue and was able to quickly identify it.

**Comment by Quitch** [comment]
Fixed by 70396d9ff295163061f6dff4b9e15819926d6d03
