### ISSUE TITLE
[BUG] Can't build Manhantan vehicle in Unit Canon

### ISSUE THREAD

**Issue by SV-Evillevi** [Quitch/GW-AI-Overhaul#37]
## Attestation

[X] I have verified this bug with all other mods disabled

[X] I am not using one of the documented [incompatible mods](https://github.com/Quitch/GW-AI-Overhaul#incompatible-mods)

[X] I have confirmed this happens after [verifying the games files](https://support.planetaryannihilation.com/kb/faq.php?id=188)

[X] I was using the latest [graphics drivers](https://support.planetaryannihilation.com/kb/faq.php?id=218)

## Describe the bug

Can't build the Manhanttan vehicle in Unit Canon as Paratrooper CEO

## To Reproduce

Steps to reproduce the behaviour:

1. Pick paratrooper CEO
2. Get the complete Vehicle card
3) build Unit canon and try to build manhantan

## Expected behaviour

that the Manhantan can be built or that it's not in the build menu if it's not intended to be built 

## GWO Info

Taken from the top-right GWO panel:

- Version: 5.39.3
- Difficulty: Silver
- Size: Large
- AI: Silver
- Options:Faction Scaling,Simple system, Easier start

## Logs

Please attach the most recent [client and serv
[PA-2022-07-14_162615.txt](https://github.com/Quitch/GW-AI-Overhaul/files/9110269/PA-2022-07-14_162615.txt)
er log](https://support.planetaryannihilation.com/kb/faq.php?id=182) immediately following the bug occurring.

**Comment by SV-Evillevi** [comment]
[PA-2022-07-14_162615.txt](https://github.com/Quitch/GW-AI-Overhaul/files/9110271/PA-2022-07-14_162615.txt)

**Comment by Quitch** [comment]
Goddamn, you're getting too good at bug reports, how am I going to ignore this now? :)

Thanks for the report, I'll see what's going on there.

**Comment by Quitch** [comment]
CEO Commander loadout is different from Paratrooper loadout. Presumably this is Paratrooper, yes?

**Comment by SV-Evillevi** [comment]
God I mistype

Ya it's the Paratrooper loadout. I blame the lack of ZZZZZ

**Comment by Quitch** [comment]
Identified the cause, working on a fix.
