### ISSUE TITLE
[BUG] Friendly ally commander not working using space Ext loadout

### ISSUE THREAD

**Issue by SV-Evillevi** [Quitch/GW-AI-Overhaul#42]
## Attestation

[X] I have verified this bug with all other mods disabled

[X] I am not using one of the documented [incompatible mods](https://github.com/Quitch/GW-AI-Overhaul#incompatible-mods)

[X] I have confirmed this happens after [verifying the games files](https://support.planetaryannihilation.com/kb/faq.php?id=188)

[X] I was using the latest [graphics drivers](https://support.planetaryannihilation.com/kb/faq.php?id=218)

## Describe the bug

Ally commander doesn't work and goes afk . I was using blue faction and Space Ext loadoutwhen this bug happened

## To Reproduce

Steps to reproduce the behaviour:

1.pick space extractor loadout
2. Go play a game with an ally commander

## Expected behaviour

Ally commander should work or not be offered if the intention is that the Space Ext loadout get's no ally
## GWO Info

Taken from the top-right GWO panel:

- Version: 5.39.3
- Difficulty: GOld
- Size:Large
- AI:Penchant
- Options:Faction scaling easier start

## Logs

Please attach the most recent [client and server log](https://support.planetaryannihilation.com/kb/faq.php?id=182) immediately following the bug occurring.
[PA-2022-07-16_123730.txt](https://github.com/Quitch/GW-AI-Overhaul/files/9125171/PA-2022-07-16_123730.txt)

**Comment by Quitch** [comment]
Can you please attach your server log.

**Comment by Quitch** [comment]
The bug here is that you shouldn't be being dealt Sub Commanders at all when using this loadout.

**Comment by Quitch** [comment]
Scratch that, I know what the issue is. This loadout isn't supposed to receive Sub Commanders because it doesn't work with them, but the new ally system doesn't account for that. Will need to consider how best to fix this.

**Comment by Quitch** [comment]
Unfortunately there seem to be a lot of hardcoded engine shenanigans going on which impact trying to open with an Orbital Launcher. Due to this for now I'm going the simpler route of disabling allies during war setup if this is your loadout.
