### ISSUE TITLE
[BUG] Cluster ally when playing has Sub Commanders leads to enemy AIs not spawning

### ISSUE THREAD

**Issue by laodie666** [Quitch/GW-AI-Overhaul#44]
## Attestation

[yes] I have verified this bug with all other mods disabled

[ yes] I am not using one of the documented [incompatible mods](https://github.com/Quitch/GW-AI-Overhaul#incompatible-mods)

[ yes] I have confirmed this happens after [verifying the games files](https://support.planetaryannihilation.com/kb/faq.php?id=188)

[ yes] I was using the latest [graphics drivers](https://support.planetaryannihilation.com/kb/faq.php?id=218)

## Describe the bug

As the title describes, when entering a system with a ally commander the no one else spawn in and the player instantly wins the game. 

## To Reproduce

Steps to reproduce the behaviour:

1. Find any system with ally commander
2. Enter battle and you will see no other commander on top left. 
3. Spawn in and instantly win.

## Expected behaviour

A normal battle should occur with an extra subcommander on the player's team. 

## GWO Info

Taken from the top-right GWO panel:

![image](https://user-images.githubusercontent.com/93632952/179372416-ec7a29ef-731d-4b7f-8c30-32a1b2eb30bf.png)

## Logs

Please attach the most recent [client and server log](https://support.planetaryannihilation.com/kb/faq.php?id=182) immediately following the bug occurring.

[server-2022-07-16_125729.txt](https://github.com/Quitch/GW-AI-Overhaul/files/9126625/server-2022-07-16_125729.txt)

**Comment by Quitch** [comment]
Please attach the client log.

Please provide a screenshot of the system you're fighting on.

**Comment by laodie666** [comment]
[PA-2022-07-16_125113.txt](https://github.com/Quitch/GW-AI-Overhaul/files/9126637/PA-2022-07-16_125113.txt)

I finished the battle already so the system is unavailable.

**Comment by Quitch** [comment]
This issue appears to occur if:

a) the player is Cluster
b) the player has more than one Sub Commander

It does not appear to matter which ally or Sub Commanders are present, only the numbers of them.

**Comment by Quitch** [comment]
I think I have the cause. It's not related to allies, rather it's when you have three or more Cluster Sub Commanders/allies total.
