### ISSUE TITLE
[BUG] Defender personality sub commander incapable of expanding

### ISSUE THREAD

**Issue by laodie666** [Quitch/GW-AI-Overhaul#48]
## Attestation

[ ye] I have verified this bug with all other mods disabled

[ye ] I am not using one of the documented [incompatible mods](https://github.com/Quitch/GW-AI-Overhaul#incompatible-mods)

[ ye] I have confirmed this happens after [verifying the games files](https://support.planetaryannihilation.com/kb/faq.php?id=188)

[ ye] I was using the latest [graphics drivers](https://support.planetaryannihilation.com/kb/faq.php?id=218)

## Describe the bug

Defender personality sub commander incapable of expanding to build more factories and take metal depots. 

This COULD be caused by factory upgrade tech but I doubt that's the case as I remember it occurred before I got the tech.

## To Reproduce

Steps to reproduce the behaviour:

1. get a defender sub commander 
2. go into  game
3. this COULD be caused by factory upgrade tech but that's unclear

## Expected behaviour

sub commander able to build more than 2 facotries

## Screenshots

![image](https://user-images.githubusercontent.com/93632952/179781054-48cfb77c-1d37-44a8-bd86-d1ca65278307.png)

![image](https://user-images.githubusercontent.com/93632952/179781009-1e02172c-90f6-42c8-b9f0-818b72a1a1a6.png)

## GWO Info

Taken from the top-right GWO panel:

![image](https://user-images.githubusercontent.com/93632952/179781168-c4b3dafa-6e54-484a-a86e-d605e50bd0dd.png)

## Logs

Please attach the most recent [client and server log](https://support.planetaryannihilation.com/kb/faq.php?id=182) immediately following the bug occurring.

[server-2022-07-19_103807.txt](https://github.com/Quitch/GW-AI-Overhaul/files/9142219/server-2022-07-19_103807.txt)

Cant attach these due to unsupported file type, how else I can upload them
![image](https://user-images.githubusercontent.com/93632952/179781451-2dafb753-f27e-4ff6-b1f9-11e2fb5f7932.png)

**Comment by laodie666** [comment]
https://drive.google.com/file/d/1diNvCA4sftx5RKQ_izuEdO45mKyTAcyp/view?usp=sharing
google drive link

**Comment by laodie666** [comment]
So I realized this could be not a bug but rather an issue with the ai. The ai would want to build a t2 factory when eco overflow rather than building more t1 factory. This combined with the fact that I'm playing legonis, and I only have vehicle factory upgrade tech and no complete vehicle tech results in sub commander not knowing what to build. I hvnt got a complete vehicle tech yet in my run but that's my best guess. tho intuitively I thought ai when have no t2 to build will just build more t1.

**Comment by laodie666** [comment]
suspecting its casued by the fact that i only have vehicle upgrade tech but i dont have complete vehical tech. as a player factory upgrade tech obsoletes t2 factory but ai will still try to build it. Considering how legonis like vehical, and i dont have t2 vehicle tech, they cant t2 properly.

**Comment by Quitch** [comment]
For future reference the easiest way to attach the file is to zip and attach the localstore folder.

**Comment by Quitch** [comment]
I'm afraid I am unable to replicate this problem. When attacking planets via your save Mjon operates about as well as any other sub commander. When using the Defender personality in sandbox conditions I also am unable to identify any problems with its operation.

This could be as specific as certain planets, or tech combinations. I would likely need a save at the exact point in time in the war you encounter the issue.
