### ISSUE TITLE
[BUG] I Can't progress on galaxy map, saves rollback to before

### ISSUE THREAD

**Issue by ConAnd81** [Quitch/GW-AI-Overhaul#60]
## Attestation

[x] I have verified this bug with all other mods disabled

[x] I am not using one of the documented [incompatible mods](https://github.com/Quitch/GW-AI-Overhaul#incompatible-mods)

[x] I have confirmed this happens after [verifying the games files](https://support.planetaryannihilation.com/kb/faq.php?id=188)

[x] I was using the latest [graphics drivers](https://support.planetaryannihilation.com/kb/faq.php?id=218)

## Describe the bug

When playing today, after I have played and won the battle in the second system(not counting the two free systems) on the galaxy map, I rollback to after I've won the first system. Playing the second system(same or any other one doesn't matter) again, rolls me back to after the win after the second battle, once again, so I can't progress.

## To Reproduce

Steps to reproduce the behaviour:
1. Start a game: small galaxy, titans AI, Expanded, GW-Silver(have tried gold as well), the six checkboxes[-][x][x][-][-][-][x], any commander(General for easy AFK wins while testing, have tried others as well, make no difference)
2. Pick up the two free Tech Cards from the two unoccupied systems.
3. Pick any enemy occupied system to do the first Battle.
4. After(hopefully) winning first Battle, you now stand in the conquered system.
5. Explore it and pick a third Tech Card
6. Then pick a second enemy occupied system and battle that commander/s.
7. After winning second battle, I am now back to "4.", in the same system I earlier won my first battle in and am about to explore it and pick my third tech card again(as if I never picked a third one). The system I picked in "6." is now occupied again.

4.->5.->6.->7.->4. will loop add infinitum(probably, have only tried to loop it three times), even if you take another system in step 5. It clearly loads the autosave from after winning battle in step 4, maybe instead of doing another autosave, I dunno.

## Expected behaviour

Short and bitter sweet, I expected the game to progress, not kicking me back to the previous system, effectively erasing my progress.

## Screenshots
Sorry, gonna have to use your imagination on this one.
## GWO Info

Taken from the top-right GWO panel:

- Version: 5.45.4
- Difficulty: Silver
- Size: Small
- AI: Titans
- Options: Faction Scaling, System Scaling

## Additional context

I've only played on small galaxies for the moment, trying to unlock all the new commanders, so I haven't tried anything larger, shouldn't really matter.
I've tried this several times now, 6 times, maybe 7, with the same result every time. Have restarted the game several times and have tried to disable the mod, test regular Galactic War(no rollback issue there), re-enable the mod, restart game, try again, same issue.
(Also, an unrelated issue, when trying regular GW after disabling GWO, the General Commander had Three slots, and all of them were free. The two "support commander tech cards" were not even there in any of the slots, but they still showed up in combat. I'm not going back to regular GW, so I don't really care, but might be worth looking into why the mod doesn't clean up after itself when disabled.)
Saw you made an update very recently, might be related. Though, from reading said logs, sounds far fetched, didn't sound related at all. I've been playing pretty frequently over the past week, and the latest updated is from Friday(2022-08-12), and I've been playing at least a little every day during the weekend. Since the game looks for updates for active mods at startup(it claims it does at least), I've at least had the update while paying yesterday(Sunday(I tend to leave games on while AFK/sleeping)), but this only started happening today(Monday). 
My memory is a bit foggy after troubleshooting this for so long today, but I think it might've started randomly in the same gaming session, after clearing a small galaxy without issue, then having the issue when starting a new galaxy without shutting down the game-client. But I could be wrong about that, since sometimes --for some reason-- the GW-intro video does not load(after pressing "go to war" the client window just goes black(can still see edge UI) and remains unresponsive) and I have to restart the whole game-client. Happens fairly often, so maybe I got the update when restarting the game after that, depending on how slow or fast PA:T is when updating mods.

## Logs

The logs are from the most recent game session strictly from starting the game, and then loading latest savegame that was at stuck at "Step 4.", so the logs only include when I play "steps 4-7" and rolling back to step 4. So the bug should be in there, but might miss a few crucial clues from the beginning steps. I have so many logs from the past two days(51), dunno which is which. Besides, I have probably wasted 8h troubleshooting this already, on my vacation no less. I've done my best to do my due diligence, but I'm going out of town tomorrow, so I'm out, can't promise I'll be able to provide you with any additional feedback within any reasonable time, sorry.

Please attach the most recent [client **AND** server logs](https://support.planetaryannihilation.com/kb/faq.php?id=182) immediately following the bug occurring.
[PA-2022-08-15_161351.txt](https://github.com/Quitch/GW-AI-Overhaul/files/9337879/PA-2022-08-15_161351.txt)
[server-2022-08-15_162127.txt](https://github.com/Quitch/GW-AI-Overhaul/files/9337881/server-2022-08-15_162127.txt)

**Comment by Quitch** [comment]
Can reproduce. Investigating.

**Comment by ConAnd81** [comment]
Welp, I just tried the only basic thing I had not tried yet, just to be sure; restarting my computer. That seemingly resolved the issue, had an windows update waiting, might have been the issue.

Might want to include that step in the "Attestation". <;-)

**Comment by Quitch** [comment]
Wasn't able to reproduce (but thanks for the excellent detail!) and the user says this is now working for them.
