### ISSUE TITLE
Interference with my AI

### ISSUE THREAD

**Issue by Donnadonnam** [Quitch/GW-AI-Overhaul#69]
https://github.com/Quitch/GW-AI-Overhaul/blob/effc889ac84d21870fb23a6745d869f13be13d80/ui/mods/com.pa.quitch.gwaioverhaul/shared/unit_groups.js#L1

**Comment by Donnadonnam** [comment]
-save

**Comment by Quitch** [comment]
Doesn't follow bug report template.
