### ISSUE TITLE
Units freeze mid battle - unplayable afterwards

### ISSUE THREAD

**Issue by Mochito35** [Quitch/GW-AI-Overhaul#78]
I think i discovered a bug, possibly related to GW-AI-Overhaul for Planetary Annihilation Titans.

What happens:
When I play galactic war, during a battle, units completely freeze. I can select them with my mouse, i can spin the planet, i can zoom in etc., but all units and explosions are static. Note that this happens during the first battle in galactic war with GW-AI-Overhaul active, not on vanilla. This problem has been noted by multiple players in steam troubleshooting discussions.

Mods installed during playthrough:
Galactic War Overhaul, PA Chat, WPMarshall's Map Pack, More Pew Pew, Milkyway Skybox, System Sharing for Titans & Classic

*My PC setup is more than powerful enough, nevertheless I play on medium details as to not lag on gigantic battles full of orbital units etc.

What will I try next:
I will try to disable all mods, especially more pew pew and test it again and see how the works.

Picture with performance analysis on the upper right corner (also as you can see, the game is not PAUSED, nor already over, this is a battle in session):
![frozen](https://user-images.githubusercontent.com/77881905/232500800-6e06b6a9-dfe9-4ba9-8263-64fc6db41c53.png)

**Comment by Quitch** [comment]
To be reported without other mods present using bug reporting template.
